on:
  issues:
    types: [assigned]
jobs:
  Add_New_Issue_To_Project:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/actions-add-new-issue-to-column@v3
      with:
        action-token: "${{ secrets.GHPROJECT_TOKEN  }}"
        project-url: "https://github.com/users/MateoBirkic/projects/1"
        column-name: "Todo"
        
        
        
